apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-provisioning-api
  labels:
    demo: nfs-pvc-provisioning
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 100Gi