apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      # volumes:
      # - name: data
      #   persistentVolumeClaim:
      #     claimName: pvc1
      containers:
      - name: api
        image: peychevi/k8s-api:1.0.2
        ports:
        - containerPort: 3000
        env:
          - name: PORT
            value: "3000"
        # volumeMounts:
        # - mountPath: /data
        #   name: data