apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: api
        image: peychevi/k8s-ui:1.0.2
        ports:
        - containerPort: 3005
        env:
          - name: PORT
            value: "3005"
          - name: API_HOST
            value: "api-service"
          - name: API_PORT
            value: "80"
