apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: peychevi/k8s-ui:1.0.3
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health-check
            port: 3005
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health-check
            port: 3005
            scheme: HTTP
          initialDelaySeconds: 2
          periodSeconds: 5
        ports:
        - containerPort: 3005
        env:
          - name: PORT
            value: "3005"
          - name: API_HOST
            value: "api-service"
          - name: API_PORT
            value: "80"
      initContainers:
      - name: check-api
        image: busybox
        command: ['sh', '-c', 'until nslookup api-service; do echo waiting for api; sleep 2; done;']
