apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: api-vertical-autoscaler
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       api-1.0.3
  updatePolicy:
    updateMode: "Auto"