apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: ui-vertical-autoscaler
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       ui-1.0.4
  updatePolicy:
    updateMode: "Auto"