apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-ssd-storage
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Premium_LRS
  kind: Managed
reclaimPolicy: Retain