apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-aws-ssd-storage
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  iopsPerGB: "50"
  fsType: ext4
  encrypted: "true"
reclaimPolicy: Retain
volumeBindingMode: Immediate