apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ipeychev-com
  namespace: default
spec:
  secretName: ipeychev-com-tls-production
  issuerRef:
    name: letsencrypt-production
  commonName: ipeychev.com
  dnsNames:
  - ipeychev.com
  - www.ipeychev.com