apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ui-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    # 1. install nginx controller: helm install -n client1 client1-nginx stable/nginx-ingress
    # 2. add the above line
    # 3. this will create a service:
    # my-nginx-nginx-ingress-controller        LoadBalancer   10.100.108.56    a069560f8405311ea8cb006df569d935-1746800378.eu-central-1.elb.amazonaws.com   80:30467/TCP,443:31808/TCP   64m
    # my-nginx-nginx-ingress-default-backend   ClusterIP      10.100.159.33    <none>                                                                       80/TCP                       64m
    # 4. create a CNAME record to iliyanpeychev.com, for example www -> a069560f8405311ea8cb006df569d935-1746800378.eu-central-1.elb.amazonaws.com
    # 5. Voilà
  namespace: default
spec:
  tls:
  - hosts:
    - www.iliyanpeychev.com
    secretName: iliyanpeychev-com-tls-production
  rules:
  - host: www.iliyanpeychev.com
    http:
      paths:
      - path: /
        backend:
          serviceName: ui-service
          servicePort: 80