apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ui-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
  namespace: default
spec:
  rules:
  - host: ppt.irinapeycheva.com
    http:
      paths:
      - backend:
          serviceName: ui-service
          servicePort: 80
        path: /*
  - host: portal.irinapeycheva.com
    http:
      paths:
      - backend:
          serviceName: ui-service
          servicePort: 80
        path: /*