apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ui-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
  namespace: default
spec:
  tls:
  - hosts:
    - iliyanpeychev.com
    secretName: iliyanpeychev-com-tls-production
  rules:
  - host: iliyanpeychev.com
    http:
      paths:
      - path: /
        backend:
          serviceName: ui-service
          servicePort: 80