apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ui-ingress
  namespace: default
spec:
  rules:
  - host: ipeychev.com
    http:
      paths:
      - backend:
          serviceName: ui-service
          servicePort: 80
        path: /*
  - host: www.ipeychev.com
    http:
      paths:
      - backend:
          serviceName: ui-service
          servicePort: 80
        path: /*
  tls:
  - secretName: ipeychev-com-tls-production