apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ui-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
  namespace: default
spec:
  backend:
    serviceName: ui-service
    servicePort: 80