apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: pvc1
      containers:
      - name: api
        image: peychevi/k8s-api:1.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: PORT
            value: "3000"
          - name: DATA_DIR
            value: /data
        volumeMounts:
        - mountPath: /data
          name: data