apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-1.0.3
  labels:
    ver: "1.0.3"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-1.0.3
      ver: "1.0.3"
  template:
    metadata:
      labels:
        app: api-1.0.3
        ver: "1.0.3"
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: nfs
      containers:
      - name: api
        image: peychevi/k8s-api:1.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: PORT
            value: "3000"
          - name: DATA_DIR
            value: /data
          - name: NODE_ENV
            value: production
        volumeMounts:
        - mountPath: /data
          name: data