apiVersion: "v1"
kind: "Service"
metadata:
  name: "api-service"
  namespace: "default"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 3000
  selector:
    app: "api-1.0.3"
  type: "ClusterIP"
